version: '2.1'
services:
  app:
    image: 'functionalmodel:tag'
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    ports:
      - 80:80
  db:
    image: mdillon/postgis
    restart: always
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./entrypoint.sh:/var/lib/postgresql/entrypoint.sh
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 3s
      timeout: 5s
      retries: 5
  adminer:
    image: adminer
    ports:
      - 8080:8080
volumes:
  postgres_data:
    driver: local