"""Initial migration.

Revision ID: 36849cfec4b7
Revises: 
Create Date: 2023-10-20 10:25:56.309856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36849cfec4b7"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dataset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("project", sa.String(length=200), nullable=False),
        sa.Column("units_cloudpath", sa.String(length=200), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "stimulus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("stimulus_cloudpath", sa.String(length=200), nullable=False),
        sa.Column("stimulus_metadata_cloudpath", sa.String(length=200), nullable=False),
        sa.Column("length", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "functionalmodel",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("replaced_by", sa.Integer(), nullable=True),
        sa.Column("dataset_id", sa.Integer(), nullable=True),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["dataset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["replaced_by"],
            ["functionalmodel.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "response",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stimulus_id", sa.Integer(), nullable=True),
        sa.Column("model_id", sa.Integer(), nullable=True),
        sa.Column("responses_cloudpath", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"],
            ["functionalmodel.id"],
        ),
        sa.ForeignKeyConstraint(
            ["stimulus_id"],
            ["stimulus.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("response")
    op.drop_table("functionalmodel")
    op.drop_table("stimulus")
    op.drop_table("dataset")
    # ### end Alembic commands ###
